controller_manager:
  ros__parameters:
    update_rate: 100

    propellor_1_controller:
      type: velocity_controllers/JointGroupVelocityController

propellor_1_controller:
  ros__parameters:
    joints:
      - helicopter_body_propellor_1
    interface_name: velocity
