controller_manager:
  ros__parameters:
    update_rate: 100

    propellor_controller:
      type: velocity_controllers/JointGroupVelocityController

propellor_controller:
  ros__parameters:
    joints:
      - body_propellor_up_joint
      - body_propellor_down_joint
    interface_name: velocity
